#!/usr/bin/env bash

flatpak install flathub com.obsproject.Studio
flatpak install flathub org.audacityteam.Audacity
flatpak install flathub org.kde.kdenlive
flatpak install flathub org.pulseaudio.pavucontrol
flatpak install flathub com.github.artemanufrij.graphui
flatpak install flathub io.dbeaver.DBeaverCommunity
flatpak install flathub rest.insomnia.Insomnia
flatpak install flathub org.gnu.emacs
flatpak install flathub app.resp.RESP # gui for redis
flatpak install flathub com.github.carlos157oliveira.Calculus
flatpak install flathub net.ankiweb.Anki
flatpak install flathub org.octave.Octave
flatpak install flathub org.stellarium.Stellarium
flatpak install flathub net.scribus.Scribus
flatpak install flathub org.blender.Blender
flatpak install flathub org.gimp.GIMP
flatpak install flathub org.inkscape.Inkscape
flatpak install flathub org.kde.krita
flatpak install flathub com.jgraph.drawio.desktop
flatpak install flathub io.github.Figma_Linux.figma_linux
flatpak install flathub com.discordapp.Discord
flatpak install flathub com.brave.Browser
flatpak install flathub com.github.micahflee.torbrowser-launcher
flatpak install flathub com.microsoft.Edge
flatpak install flathub com.valvesoftware.Steam
flatpak install flathub io.gitlab.librewolf-community
flatpak install flathub org.chromium.Chromium
flatpak install flathub org.mozilla.firefox
flatpak install flathub org.onionshare.OnionShare
flatpak install flathub org.qbittorrent.qBittorrent
flatpak install flathub com.github.marktext.marktext
flatpak install flathub md.obsidian.Obsidian
flatpak install flathub org.onlyoffice.desktopeditors
flatpak install flathub io.github.narunlifescience.AlphaPlot
flatpak install flathub org.kde.dolphin
flatpak install flathub dev.boxi.Boxi
flatpak install flathub com.raggesilver.BlackBox
flatpak install flathub io.github.arunsivaramanneo.GPUViewer
flatpak install flathub com.mongodb.Compass
flatpak install flathub org.gnome.TextEditor
flatpak install flathub org.keepassxc.KeePassXC
flatpak install flathub org.libreoffice.LibreOffice
